name: newtool

on:
    schedule:
      - cron: '0 0 * * *'
    # workflow_dispatch
    # push:
    workflow_dispatch:
      inputs:
          target:
            required: false
            default: 'testfire.net'


jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TARGET: ${{ github.event.inputs.target }}
    steps:
      # - run: echo "::add-mask::$TARGET"
      - run: curl ifconfig.me
      - run: git clone --depth 1 https://github.com/c0ny1/vulstudy
      - run: cd vulstudy && docker-compose up -d
      - run: sudo netstat -tulpn | grep LISTEN

      - run: curl 0.0.0.0:83
      - run: docker run wtwver/sqlmap http://localhost:83

      - name: nuclei
        run: docker run projectdiscovery/nuclei -u https://$TARGET

      - name: jaeles
        run: docker run --entrypoint sh wtwver/jaeles -c "jaeles config init -y && jaeles scan -s '/root/.jaeles/base-signatures' -u https://$TARGET"

      - name: automated-pentest
        run: docker run --entrypoint "" -v pentest-reports:/src vishnunair/pentest:latest ./pentest.sh -d $TARGET       

#       - name: automated-pentest https
#         run: docker run --entrypoint "" -v pentest-reports:/src vishnunair/pentest:latest ./pentest.sh -d https://$TARGET    
      # - name: site1
      #   run: docker run projectdiscovery/nuclei -u https://testfire.net
      # - name: site2
      #   run: docker run projectdiscovery/nuclei -u https://preview.owasp-juice.shop
