name: Nuclei - DAST Scan

on:
    schedule:
      - cron: '0 0 * * *'
    # workflow_dispatch
    push:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --rm -it projectdiscovery/nuclei -u ${{ secrets.TARGET }}
