name: Scan Target

on:
    schedule:
      - cron: '0 0 * * *'
    # workflow_dispatch
    push:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - run: top
      - run: docker run projectdiscovery/nuclei -u ${{ secrets.HTTP }}://${{ secrets.DOMAIN }}
      - run: docker run wtwver/reconftw -d ${{ secrets.DOMAIN }} -a
