name: reconftw

on:
   # schedule:
     # - cron: '0 0 * * *'
    # workflow_dispatch
    # push:
    workflow_dispatch:
      inputs:
          target:
            required: false
            default: 'testfire.net'

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ github.event.inputs.target }}
    steps:
      - run: free -m && df -h .
      # - uses: actions/checkout@v2
      - run: wget https://raw.githubusercontent.com/wtwver/atm/main/config/reconftw.bbrf?token=AM2642AZ5QKGJWXDYJB4SYTBLAAVY -O reconftw.bbrf
      - run: wget https://raw.githubusercontent.com/wtwver/atm/main/config/provider-config.yaml?token=AM2642DAWFSV2KQZJHNRB33BLAMPA -O provider-config.yaml
      - run: ls -R
      - run: cat ${PWD}/provider-config.yaml

      - name: start service
        run: docker run -m 5g -d --name reconftw -v ${PWD}/provider-config.yaml:/root/.config/notify/provider-config.yaml -v ${PWD}/reconftw.bbrf:/root/Tools/reconftw/reconftw.cfg --entrypoint bash wtwver/reconftw -c "tail -f /dev/null"
      - run: docker exec reconftw rm ../../.bbrf/config.json
      - run: docker exec reconftw bash install.sh
      - run: docker exec reconftw sed -i '1686 a curl -T "$SCRIPTPATH/$zip_name" https://f.hoball.tk:81/upload/' reconftw.sh
            
      - name: subdomain
        run: docker exec reconftw ./reconftw.sh -d $TARGET -s
        # -H "Accept: application/vnd.github.v3+json" 
      # - name: curl
      #   run: docker exec reconftw cat Recon/$TARGET/subdomains/subdomains.txt | xargs  -L 1 -I {} curl -X POST https://api.github.com/repos/wtwver/nuclei/actions/workflows/reconftw_web.yml/dispatches -u wtwver:${{ secrets.GITHUBTOKEN }} -d '{"ref":"main" , "inputs":{"target":"{}"}}' 

      # - run:　|
      #     docker exec reconftw bash -c "cat Recon/$TARGET／subdomains/subdomains.txt webs/webs.txt 2>/dev/null | nuclei -silent -t ~/nuclei-templates/"

      - name: remove data to prevent bugs
        run: docker exec reconftw rm -rf Recon/$TARGET
      - name: all
        run: docker exec reconftw ./reconftw.sh -d $TARGET -a    
