name: sqlilab-sqlmap

on:
    schedule:
      - cron: '0 0 * * *'
    push:
    workflow_dispatch:
      # inputs:
      #     target:
      #       required: false
      #       default: 'testfire.net'


jobs:
  sqlmap:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TARGET: ${{ github.event.inputs.target }}
    steps:
      # - run: echo "::add-mask::$TARGET"
      - run: curl ifconfig.me
      
      - run : docker run -p 8765:80 acgpiano/sqli-labs &
      - run: curl localhost:8765 -I --ipv4
      
      - run: docker run wtwver/sqlmap http://localhost:8765
      - run: docker run projectdiscovery/nuclei -u http://localhost:8765

  test2:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: tail -f /dev/null