name: sqlilab

on:
    schedule:
      - cron: '0 0 * * *'
    push:
    workflow_dispatch:
      # inputs:
      #     target:
      #       required: false
      #       default: 'testfire.net'


jobs:
  sqlmap:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TARGET: ${{ github.event.inputs.target }}
    steps:
      # - run: echo "::add-mask::$TARGET"
      - run: curl ifconfig.me && ip a
      - run: curl -s https://install.zerotier.com | sudo bash
      - run: sudo zerotier-cli join 8286ac0e473ee80d

      - run: docker network create test1
      - run: docker run --name lab --net test1 -p 1000:80 -d acgpiano/sqli-labs 
      - run: docker exec lab apt-get update && docker exec lab apt-get install -y curl
      - run: docker exec lab curl http://localhost/sql-connections/setup-db.php

      - run: sudo netstat -tulpn | grep LISTEN 

      - run: docker run --net test1 wtwver/hakrawler hakrawler -url http://lab/ -depth 5 -plain -wayback
      - run: docker run --net test1 -e a=http://lab wtwver/hakrawler2 

      # - run: docker run --net test1 wtwver/sqlmap http://lab/Less-1/?id=1 --risk 3 --level 5
      - run: for a in {1..65}; do echo $a ; done
      # - run: for a in {1..65}; do docker run --net test1 wtwver/sqlmap http://lab/Less-$a/?id=1 --risk 3 --level 5 ; done
      
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-1/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-2/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-3/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-4/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-5/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-6/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-7/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-8/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-9/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-10/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-11/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-12/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-13/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-14/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-15/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-16/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-17/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-18/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-19/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-20/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-21/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-22/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-23/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-24/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-25/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-26/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-27/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-28/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-29/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-30/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-31/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-32/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-33/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-34/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-35/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-36/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-37/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-38/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-39/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-40/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-41/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-42/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-43/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-44/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-45/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-46/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-47/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-48/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-49/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-50/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-51/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-52/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-53/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-54/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-55/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-56/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-57/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-58/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-59/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-60/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-61/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-62/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-63/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-64/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-65/?id=1 --risk 3 --level 5
            
      - run: curl 172.17.0.1:1000 -I 
      - run: curl localhost:1000 -I 

      # - run: tail -f /dev/null
