name: sqlilab-sqlmap

on:
    schedule:
      - cron: '0 0 * * *'
    push:
    workflow_dispatch:
      # inputs:
      #     target:
      #       required: false
      #       default: 'testfire.net'


jobs:
  sqlmap:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TARGET: ${{ github.event.inputs.target }}
    steps:
      # - run: echo "::add-mask::$TARGET"
      - run: curl ifconfig.me
      
      - run : docker run -p 8765:80 acgpiano/sqli-labs &
      - run: curl localhost:8765 -I --ipv4
      
      - run: docker run wtwver/sqlmap http://localhost:8765
      - run: docker run projectdiscovery/nuclei -u http://localhost:8765

  docker:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          repository: canonical-web-and-design/vanilla-framework
      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag testrun .
      - name: Run server with Docker
        run: docker run -p 8765:80 --env SECRET_KEY=insecure_test_key testrun &
      - name: Check server status
        run: curl localhost:8765/_status/check -I
      - name: Run server with Docker
        run: docker run -p 8766:80 acgpiano/sqli-labs &
      - name: Check server status
        run: curl localhost:8766/_status/check -I
      - name: Install linkchecker
        run: sudo pip install LinkChecker
      - name: Check internal links
        run: linkchecker --ignore-url /search http://localhost:8765