name: sqlilab-sqlmap

on:
    schedule:
      - cron: '0 0 * * *'
    push:
    workflow_dispatch:
      # inputs:
      #     target:
      #       required: false
      #       default: 'testfire.net'


jobs:
  sqlmap:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TARGET: ${{ github.event.inputs.target }}
    steps:
      # - run: echo "::add-mask::$TARGET"
      - run: curl ifconfig.me && ip a
      
      - run: docker run -p 1000:80 acgpiano/sqli-labs &
      - run: sudo netstat -tulpn | grep LISTEN 

      - run: docker run wtwver/sqlmap http://172.17.0.1:1000 --crawl 3
      - run: docker run projectdiscovery/nuclei -u http://172.17.0.1:1000

      - run: curl 172.17.0.1:1000 -I 
      - run: curl localhost:1000 -I 