name: sqlilab-sqlmap

on:
    schedule:
      - cron: '0 0 * * *'
    push:
    workflow_dispatch:
      # inputs:
      #     target:
      #       required: false
      #       default: 'testfire.net'


jobs:
  sqlmap:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TARGET: ${{ github.event.inputs.target }}
    steps:
      # - run: echo "::add-mask::$TARGET"
      - run: curl ifconfig.me && ip a
      - run: curl -s https://install.zerotier.com | sudo bash
      - run: zerotier-cli join 8286ac0e473ee80d

      - run: docker network create test1
      - run: docker run --name lab --net test1 -p 1000:80 -d acgpiano/sqli-labs 
      - run: docker exec lab apt-get update && docker exec lab apt-get install -y curl
      - run: docker exec lab curl http://localhost/sql-connections/setup-db.php

      - run: sudo netstat -tulpn | grep LISTEN 

      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-1/?id=1 --risk 3 --level 5
      - run: docker run --net test1 wtwver/sqlmap http://lab/Less-50/?id=1 --risk 3 --level 5
      - run: curl 172.17.0.1:1000 -I 
      - run: curl localhost:1000 -I 

      - run: tail -f /dev/null