name: sqlilab-sqlmap

on:
    schedule:
      - cron: '0 0 * * *'
    push:
    workflow_dispatch:
      # inputs:
      #     target:
      #       required: false
      #       default: 'testfire.net'


jobs:
  sqlmap:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TARGET: ${{ github.event.inputs.target }}
    steps:
      # - run: echo "::add-mask::$TARGET"
      - run: curl ifconfig.me
      
      - run: docker run -p 8765:80 acgpiano/sqli-labs &
      - run: curl 172.18.0.1:8765 -I 
      
      - run: docker run wtwver/sqlmap http://172.18.0.1:8765
      - run: docker run projectdiscovery/nuclei -u http://172.18.0.1:8765