name: Scan vulnerable

on:
    schedule:
      - cron: '0 0 * * *'
    # workflow_dispatch
    # push:
    workflow_dispatch:
      inputs:
          target:
            required: false
            default: 'testfire.net'


jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ github.event.inputs.target }}
    steps:
      # - run: echo "::add-mask::$TARGET"
      - run: curl ifconfig.me
      - name: input
        run: docker run projectdiscovery/nuclei -u https://$TARGET
      - name: site1
        run: docker run projectdiscovery/nuclei -u https://testfire.net
      - name: site2
        run: docker run projectdiscovery/nuclei -u https://preview.owasp-juice.shop
