name: Scan vulnerable

on:
    schedule:
      - cron: '0 0 * * *'
    # workflow_dispatch
    # push:
    workflow_dispatch:
        inputs:
          target:
            required: true
            default: 'testfire.net'

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.target }} && curl ifconfig.me
      - run: docker run projectdiscovery/nuclei -u https://testfire.net
      - run: docker run projectdiscovery/nuclei -u https://preview.owasp-juice.shop
