name: Scan vulnerable

on:
    schedule:
      - cron: '0 0 * * *'
    # workflow_dispatch
    # push:
    workflow_dispatch:
      inputs:
          target:
            required: false
            default: 'testfire.net'


jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ github.event.inputs.target }}
    steps:
      - run: echo "::add-mask::$TARGET"
      - name: lol
        run: echo ${{ github.event.inputs.target }} && curl ifconfig.me
      - run: docker run projectdiscovery/nuclei -u https://testfire.net
      - run: docker run projectdiscovery/nuclei -u https://preview.owasp-juice.shop
